site_name: Seafile Best Practise
site_url: http://seafile-best-practise.readthedocs.io/
site_description: Seafile Best Practise documentation with Markdown.
site_author: DerDanilo, Wolle

repo_url: https://github.com/DerDanilo/Seafile-Best-Practise

pages:
- Home: 'index.md'
- General:
    - 'Contribution': 'general/contribution.md'
    - 'Updates': 'general/updates.md'
    - 'Changelog': 'general/changelog.md'
    - 'System requirements': 'general/system-requirements.md'
    - 'About': 'general/about.md'
- Installation:
    - 'OperatingSystem': 'installation/operating-system.md'
    - 'IP': 'installation/ip.md'
    - 'DNS': 'installation/dns.md'
    - 'Webserver Nginx': 'installation/webserver-nginx.md'
    - 'Lets Encrypt': 'installation/le.md'
    - 'Seafile Setup': 'installation/seafile-setup.md'
    - 'Office':
        - 'OnlyOffice': 'installation/office/onlyoffice.md'
        - 'Collabora': 'installation/office/collabora.md'
- Update: 'update/update.md'
- Config-files:
    - 'Seafile':
        - 'Ccnet': 'config_files/seafile/ccnet.md'
        - 'Seafile': 'config_files/seafile/seafile.md'
        - 'Seahub': 'config_files/seafile/seahub.md'
    - 'Fail2ban': 'config_files/fail2ban.md'
    - 'Firewall nft': 'config_files/firewall-nft.md'
    - 'Firewall firewalld': 'config_files/firewall-firewalld.md'
- Backup/Restore:
    - 'Backup': 'backup_restore/backup.md'
    - 'Restore': 'backup_restore/restore.md'
markdown_extensions:
    - toc:
        permalink:
    - admonition:

copyright: Copyright &copy; 2017 <a href="https://forum.seafile.com">DerDanilo, Wolle - Seafile Community</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Seafile Community</a>.