site_name: Seafile Best Practise
site_url: http://seafile-best-practise.readthedocs.io/
site_description: Seafile Best Practise documentation with Markdown.
site_author: DerDanilo, Wolle

repo_url: https://github.com/DerDanilo/Seafile-Best-Practise

pages:
- Home: index.md
- General:
    - Contribution: general/contribution.md
    - Updates: general/updates.md
    - Changelog: general/changelog.md
    - System requirements: general/system-requirements.md
    - About: general/about.md
- Installation:
    - OperatingSystem: installation/operatingsystem.md
    - IP: installation/ip.md
    - DNS: installation/dns.md
	- Webserver Nginx: installation/webserver-nginx.md
    - LetsEncrypt: installation/LE.md
	- Seafile Setup: installation/seafile-setup.md
    - Office:
		- OnlyOffice: installation/office/onlyoffice.md
		- Collabora: installation/office/collabora.md
- Update: update/update.md
- Config-files:
    - Seafile: config-files/seafile/overview.md
		- ccnet: config_files/seafile/ccnet.md
		- seafile: config_files/seafile/seafile.md
	- Fail2ban: config-files/fail2ban.md
	- Firewall nft: config-files/firewall-nft.md
	- Firewall firewalld: config-files/firewall-firewalld.md
- Backup/Restore:
    - Backup: backup-restore/backup.md
    - Restore: backup-restore/restore.md
markdown_extensions:
    - toc:
        permalink: 
    - admonition:

copyright: Copyright &copy; 2017 <a href="https://forum.seafile.com">DerDanilo, Wolle - Seafile Community</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Seafile Community</a>.